spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library?autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: admin
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      dialect: MySQL5Dialect
      hibernate:
        ddl-auto: none
  servlet:
    multipart:
      max-file-size: 15MB
      maxRequestSize: 15MB
server:
  port: 8080